--[[
    Script Path: Game/StarterPlayer/StarterPlayerScripts/PlayerModule/CameraModule/TransparencyController
    Class: ModuleScript
    Time: 2026-10-03 12:27:04
--]]

local VRService_upv_1 = game:GetService("VRService")
local tbl_upv_1 = {"BasePart", "Decal", "Beam", "ParticleEmitter", "Trail", "Fire", "Smoke", "Sparkles", "Explosion"}
local CameraUtils_upv_1 = require(script.Parent:WaitForChild("CameraUtils"))
local success_1, v1 = pcall(
    function()
        --[[
          line: 27
        ]]
        return UserSettings():IsUserFeatureEnabled("UserHideCharacterParticlesInFirstPerson")
    end
)
local u1 = success_1 and v1
local tbl_upv_2 = {}
tbl_upv_2.__index = tbl_upv_2
function tbl_upv_2.new()
    --[[
      name: new
      line: 38
      upvalues:
        tbl_upv_2 (copy, index: 1)
    ]]
    local v2 = setmetatable({}, tbl_upv_2)
    v2.transparencyDirty = false
    v2.enabled = false
    v2.lastTransparency = nil
    v2.descendantAddedConn = nil
    v2.descendantRemovingConn = nil
    v2.toolDescendantAddedConns = {}
    v2.toolDescendantRemovingConns = {}
    v2.cachedParts = {}
    return v2
end
function tbl_upv_2.HasToolAncestor(a1, a2)
    --[[
      name: HasToolAncestor
      line: 54
    ]]
    if a2.Parent == nil then
        return false
    end
    assert(a2.Parent, "")
    local v3 = a2.Parent:IsA("Tool") or (a2.Parent:IsA("Accessory") or (a1:HasToolAncestor(a2.Parent)))
    return v3
end
function tbl_upv_2.IsValidPartToModify(a1, a2)
    --[[
      name: IsValidPartToModify
      line: 60
      upvalues:
        u1 (ref,  index: 1)
        tbl_upv_1 (copy, index: 2)
    ]]
    if u1 then
        for _, value_1 in tbl_upv_1 do
            if not (a2:IsA(value_1)) then
                continue
            end
            return a1:HasToolAncestor(a2)
        end
        return false
    elseif not (a2:IsA("BasePart")) and not (a2:IsA("Decal")) then
        return false
    else
        return a1:HasToolAncestor(a2)
    end
end
function tbl_upv_2.CachePartsRecursive(a1, a2)
    --[[
      name: CachePartsRecursive
      line: 76
    ]]
    if not a2 then
        return
    end
    if a1:IsValidPartToModify(a2) then
        a1.cachedParts[a2] = true
        a1.transparencyDirty = true
    end
    for _, value_2 in pairs(a2:GetChildren()) do
        a1:CachePartsRecursive(value_2)
    end
end
function tbl_upv_2.TeardownTransparency(a1)
    --[[
      name: TeardownTransparency
      line: 88
    ]]
    for key_1, _ in pairs(a1.cachedParts) do
        key_1.LocalTransparencyModifier = 0
    end
    a1.cachedParts = {}
    a1.transparencyDirty = true
    a1.lastTransparency = nil
    if a1.descendantAddedConn then
        a1.descendantAddedConn:disconnect()
        a1.descendantAddedConn = nil
    end
    if a1.descendantRemovingConn then
        a1.descendantRemovingConn:disconnect()
        a1.descendantRemovingConn = nil
    end
    for key_2, value_3 in pairs(a1.toolDescendantAddedConns) do
        value_3:Disconnect()
        a1.toolDescendantAddedConns[key_2] = nil
    end
    for key_3, value_4 in pairs(a1.toolDescendantRemovingConns) do
        value_4:Disconnect()
        a1.toolDescendantRemovingConns[key_3] = nil
    end
end
function tbl_upv_2.SetupTransparency(a1, a2)
    --[[
      name: SetupTransparency
      line: 114
    ]]
    a1:TeardownTransparency()
    if a1.descendantAddedConn then
        a1.descendantAddedConn:disconnect()
    end
    a1.descendantAddedConn = a2.DescendantAdded:Connect(
        function(a3)
            --[[
              line: 118
              upvalues:
                a1 (copy, index: 1)
                a2 (copy, index: 2)
            ]]
            if a1:IsValidPartToModify(a3) then
                a1.cachedParts[a3] = true
                a1.transparencyDirty = true
            elseif a3:IsA("Tool") then
                if a1.toolDescendantAddedConns[a3] then
                    a1.toolDescendantAddedConns[a3]:Disconnect()
                end
                a1.toolDescendantAddedConns[a3] = a3.DescendantAdded:Connect(
                    function(a4)
                        --[[
                          line: 126
                          upvalues:
                            a1 (copy, index: 1)
                        ]]
                        a1.cachedParts[a4] = nil
                        if not a4:IsA("BasePart") and not a4:IsA("Decal") then
                            return
                        end
                        a4.LocalTransparencyModifier = 0
                    end
                )
                if a1.toolDescendantRemovingConns[a3] then
                    a1.toolDescendantRemovingConns[a3]:disconnect()
                end
                a1.toolDescendantRemovingConns[a3] = a3.DescendantRemoving:Connect(
                    function(a5)
                        --[[
                          line: 134
                          upvalues:
                            a2 (copy, index: 1)
                            a1 (copy, index: 2)
                        ]]
                        wait()
                        if not a2 or not a5 or not a5:IsDescendantOf(a2) or not a1:IsValidPartToModify(a5) then
                            return
                        end
                        a1.cachedParts[a5] = true
                        a1.transparencyDirty = true
                    end
                )
            end
        end
    )
    if a1.descendantRemovingConn then
        a1.descendantRemovingConn:disconnect()
    end
    a1.descendantRemovingConn = a2.DescendantRemoving:connect(
        function(a6)
            --[[
              line: 146
              upvalues:
                a1 (copy, index: 1)
            ]]
            if not a1.cachedParts[a6] then
                return
            end
            a1.cachedParts[a6] = nil
            a6.LocalTransparencyModifier = 0
        end
    )
    a1:CachePartsRecursive(a2)
end
function tbl_upv_2.Enable(a1, a2)
    --[[
      name: Enable
      line: 157
    ]]
    if a1.enabled == a2 then
        return
    end
    a1.enabled = a2
end
function tbl_upv_2.SetSubject(a1, a2)
    --[[
      name: SetSubject
      line: 163
    ]]
    if a2 then
        local _ = (not a2:IsA("Humanoid")) or (a2.Parent)
    end
    local v4 = (not a2) or ((not a2:IsA("VehicleSeat")) or ((not (a2.Occupant)) or (a2.Occupant.Parent)))
    if v4 then
        a1:SetupTransparency(v4)
    else
        a1:TeardownTransparency()
    end
end
function tbl_upv_2.Update(a1, a2)
    --[[
      name: Update
      line: 178
      upvalues:
        CameraUtils_upv_1 (copy, index: 1)
        VRService_upv_1 (copy, index: 2)
    ]]
    local CurrentCamera_1 = workspace.CurrentCamera
    if not CurrentCamera_1 then
        return
    end
    if a1.enabled then
        local magnitude_1 = (CurrentCamera_1.Focus.p - CurrentCamera_1.CoordinateFrame.p).magnitude
        local v5 = ((magnitude_1 < 2) and (1 - (magnitude_1 - 0.5) / 1.5)) or 0
        if v5 < 0.5 then
            v5 = 0
        end
        if a1.lastTransparency and v5 < 1 and a1.lastTransparency < 0.95 then
            local _ = 2.8 * a2
            v5 = a1.lastTransparency + math.clamp(v5 - a1.lastTransparency, -(2.8 * a2), 2.8 * a2)
        else
            a1.transparencyDirty = true
        end
        local v6 = math.clamp(CameraUtils_upv_1.Round(v5, 2), 0, 1)
        if a1.transparencyDirty or a1.lastTransparency ~= v6 then
            for key_4, _ in pairs(a1.cachedParts) do
                if not (VRService_upv_1.VREnabled) or not (VRService_upv_1.AvatarGestures) then
                    key_4.LocalTransparencyModifier = v6
                    continue
                end
                local tbl_3 = {}
                tbl_3[Enum.AccessoryType.Hat] = true
                tbl_3[Enum.AccessoryType.Hair] = true
                tbl_3[Enum.AccessoryType.Face] = true
                tbl_3[Enum.AccessoryType.Eyebrow] = true
                tbl_3[Enum.AccessoryType.Eyelash] = true
                if key_4.Parent:IsA("Accessory") and tbl_3[key_4.Parent.AccessoryType] or key_4.Name == "Head" then
                    key_4.LocalTransparencyModifier = v6
                    continue
                end
                key_4.LocalTransparencyModifier = 0
            end
            a1.transparencyDirty = false
            a1.lastTransparency = v6
        end
    end
end
return tbl_upv_2