--[[
    Script Path: Game/StarterPlayer/StarterCharacterScripts/WalkingSoundsClient/IDlist
    Class: ModuleScript
    Time: 2026-10-03 12:27:08
--]]

local tbl_1 = {}
tbl_1.Air = {id = "rbxassetid://329997777", speed = 1, volume = 0}
tbl_1.Asphalt = {id = "rbxassetid://277067660", speed = 1, volume = 0.6}
tbl_1.Basalt = {id = "rbxassetid://3190903775", speed = 1, volume = 0.6}
tbl_1.Brick = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Cobblestone = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Concrete = {id = "rbxassetid://277067660", speed = 1, volume = 0.6}
tbl_1.CorrodedMetal = {id = "rbxassetid://177940974", speed = 1, volume = 0.6}
tbl_1.CrackedLava = {id = "rbxassetid://3190903775", speed = 1, volume = 0.6}
tbl_1.DiamondPlate = {id = "rbxassetid://177940974", speed = 1, volume = 0.6}
tbl_1.Fabric = {id = "rbxassetid://9083849830", speed = 1, volume = 0.4}
tbl_1.Foil = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Forcefield = {id = "rbxassetid://329997777", speed = 1, volume = 0.6}
tbl_1.Glass = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Granite = {id = "rbxassetid://178054124", speed = 1, volume = 0.6}
tbl_1.Grass = {id = "rbxassetid://177940963", speed = 1, volume = 0.5}
tbl_1.Glacier = {id = "rbxassetid://7047108275", speed = 1, volume = 0.4}
tbl_1.Ground = {id = "rbxassetid://9064714296", speed = 1, volume = 0.6}
tbl_1.Ice = {id = "rbxassetid://7047108275", speed = 1, volume = 0.4}
tbl_1.Limestone = {id = "rbxassetid://9083846829", speed = 1, volume = 0.6}
tbl_1.LeafyGrass = {id = "rbxassetid://3098847639", speed = 1, volume = 0.6}
tbl_1.Marble = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Metal = {id = "rbxassetid://177940974", speed = 1, volume = 0.6}
tbl_1.Mud = {id = "rbxassetid://6441160246", speed = 1, volume = 0.6}
tbl_1.Neon = {id = "rbxassetid://177940974", speed = 1, volume = 0.6}
tbl_1.Pebble = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Plastic = {id = "rbxassetid://177940963", speed = 1, volume = 0.5}
tbl_1.Pavement = {id = "rbxassetid://277067660", speed = 1, volume = 0.6}
tbl_1.Rock = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Sand = {id = "rbxassetid://9083846829", speed = 1, volume = 0.4}
tbl_1.Slate = {id = "rbxassetid://178054124", speed = 1, volume = 0.6}
tbl_1.Snow = {id = "rbxassetid://8453425942", speed = 1, volume = 0.6}
tbl_1.Salt = {id = "rbxassetid://9083846829", speed = 1, volume = 0.4}
tbl_1.Sandstone = {id = "rbxassetid://3190903775", speed = 0.75, volume = 0.6}
tbl_1.SmoothPlastic = {id = "rbxassetid://178190837", speed = 1, volume = 0.6}
tbl_1.Wood = {id = "rbxassetid://3199270096", speed = 1, volume = 0.6}
tbl_1.WoodPlanks = {id = "rbxassetid://211987063", speed = 1, volume = 0.6}
return tbl_1